### ISSUE TITLE
As a clueless year one, I want links to resume templates so that I can prepare my application to tech companies.

### ISSUE THREAD

**Issue by J0** [sushinoya/singapore-tech-internships#4]
I would like to add a section in README.md with links to some of the commonly used resume templates in SoC.

**Comment by wn** [comment]
http://www.latextemplates.com/template/friggeri-resume-cv is pretty popular too. Perhaps we can also have resume of seniors who had some success bagging large tech companies internship too, subject to their approval.

**Comment by sushinoya** [comment]
@J0 @wn Hmm tbh my opinion is that templates don't matter as much as the content. We could add sample resumes from seniors but then I think its best to reach out to a senior and ask them to go through your resume with you. That's what I've been doing.

**Comment by J0** [comment]
@sushinoya let's go with what you suggested;closing this issue.
